[template]
src = "oidc.conf.tmpl"
dest = "/etc/apache2/conf.d/openidc.conf"
prefix = "%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/etc/init.d/apache2 reload"
